name: harp
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - scipy           
  - statsmodels      
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - matplotlib
  - seaborn
  - pyyaml
  - tqdm
  - ipykernel
  - xlrd=2.0.1
  - pip:
    - python-box     
    - requests       
    - appnope        