# Data Paths
raw_input_path: "harp/data/raw/processed/cms_2008_2010_samples.csv"
output_dir_raw: "harp/data/raw/harp_dataset"
output_dir_encoded: "harp/data/raw/harp_dataset_encoded"

# Preprocessing
collect_samples: 5
sample_dir: "harp/data/raw/samples"

# Splitting
test_size: 0.15
val_size: 0.15
random_state: 42

# Corruption / Injection
injection_rate: 0.2

# Complexity Scoring Weights by Complexity Reason
scores:
  multi_payer: 3
  short_stay: 3
  surgical: 2
  high_cost: 1

# Clustering / Reviewer Settings
n_reviewers: 2
kmeans_init: 10

# Sim errors for determining d
plot_cutoffs: True
traditional_random_error: 0.95
reviewer_out_of_depth_error: 0.5

# Reviewer cost params for determining c
reviewer_cost_params:
  cost_mode: "mrr"

  mrr_penalty: 10
  mrr_base_error_rate: 0.5

  scarcity_c_base: 1