train_mode: "harp_pi"

# misc
device: "cpu"
save_dir: "harp/models/checkpoints/harp_pi"
log_interval: 1000
save_freq: 5
batch_size: 32
reviewer_costs: [2.365, 3.004]
val_freq: 5
log_dir: "logs"

# model configs

## encoder
encoding_dim: 32
numeric_dim: 7
num_enc_heads: 4
num_enc_layers: 3
dgns_vocab_size: 14435
prcdr_vocab_size: 3862

## f
f_hidden_dims: [32, 16, 8, 4]
f_drouput: 0.1
f_weights_path: "harp/models/checkpoints/f/minimal_fnet_epoch_1.pt"

## pi
pi_hidden_dims: [32, 16, 8]

## harp hyperparams
gumbel_tau: 5.0
error_penalty: 3.5 # don't collapse to always using f even if it's wrong so we have to do penalty > max(reviewer_costs)

## optimization hyperparams
bce_pos_weight: 0.2
lr: 1e-4
epochs: 100